from __future__ import annotations

import argparse
import sys
from pathlib import Path
from src.make_bridge import (
    PRESIGNED_URL_TTL_SECONDS,
    bridge_video_to_make,
)

DEFAULT_CONFIG_PATH = Path("config.yaml")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload an approved MP4 to Cloudflare R2 and forward it to Make.com."
    )
    parser.add_argument(
        "--video",
        required=True,
        help="Path to the approved .mp4 file generated by the pipeline.",
    )
    parser.add_argument(
        "--caption",
        required=True,
        help="Caption to send to the Make.com webhook.",
    )
    parser.add_argument(
        "--object-key",
        help="Optional R2 object key. Defaults to videos/<filename>-<timestamp>.mp4.",
    )
    parser.add_argument(
        "--config",
        default=str(DEFAULT_CONFIG_PATH),
        help="Optional path to config.yaml. Defaults to ./config.yaml.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    video_path = Path(args.video).expanduser().resolve()
    config_path = Path(args.config).expanduser().resolve()

    try:
        result = bridge_video_to_make(
            video_path,
            args.caption,
            object_key=args.object_key,
            config_path=config_path,
        )
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    print("Upload complete.")
    print(f"R2 object key: {result.object_key}")
    print(f"Presigned URL expires in: {PRESIGNED_URL_TTL_SECONDS // 60} minutes")
    print(f"Make.com webhook response: {result.webhook_status_code}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
